version: "3.8"

services:
  db:
    image: postgres:16
    container_name: banconova_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: banconova
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: banconova_api
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://db:5432/banconova
      DB_USER: postgres
      DB_PASS: postgres
      JWT_SECRET: CAMBIA_ESTO_POR_ALGO_LARGO_Y_SEGURO_123456789
      JWT_EXP_MS: 86400000
      CORS_ORIGINS: http://localhost:5173,http://127.0.0.1:5173
    ports:
      - "8080:8080"

volumes:
  db_data:
